// models/AirData.js
const mongoose = require('mongoose');

const AirDataSchema = new mongoose.Schema({
  PROVINCIA: { type: Number, required: true },
  MUNICIPIO: { type: Number, required: true },
  ESTACION: { type: Number, required: true },
  MAGNITUD: { type: Number, required: true },
  PUNTO_MUESTREO: { type: String, required: true },
  ANO: { type: Number, required: true },
  MES: { type: Number, required: true },
  DIA: { type: Number, required: true },

  // Campos Hxx y Vxx (los xx van de 01 a 24)  
  // Puedes ponerlos como opcionales si no siempre tienen valor
  H01: Number,
  V01: String,
  H02: Number,
  V02: String,
  H03: Number,
  V03: String,
  H04: Number,
  V04: String,
  H05: Number,
  V05: String,
  H06: Number,
  V06: String,
  H07: Number,
  V07: String,
  H08: Number,
  V08: String,
  H09: Number,
  V09: String,
  H10: Number,
  V10: String,
  H11: Number,
  V11: String,
  H12: Number,
  V12: String,
  H13: Number,
  V13: String,
  H14: Number,
  V14: String,
  H15: Number,
  V15: String,
  H16: Number,
  V16: String,
  H17: Number,
  V17: String,
  H18: Number,
  V18: String,
  H19: Number,
  V19: String,
  H20: Number,
  V20: String,
  H21: Number,
  V21: String,
  H22: Number,
  V22: String,
  H23: Number,
  V23: String,
  H24: Number,
  V24: String,
}, {
  timestamps: true,
});

module.exports = mongoose.model('AirData', AirDataSchema, 'aire');

